// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnjHEBgbCiwAaE7BGRPstYQgoIYycSe78',
    appId: '1:691213890190:web:22566a8b540fbbdd798fdf',
    messagingSenderId: '691213890190',
    projectId: 'nexevent-d5e5b',
    authDomain: 'nexevent-d5e5b.firebaseapp.com',
    storageBucket: 'nexevent-d5e5b.firebasestorage.app',
    measurementId: 'G-KK04YMFK46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3eRsiU5XB7ntzbIb-tpa_tsJuSr9UtAI',
    appId: '1:691213890190:android:9d4061ab9bfda867798fdf',
    messagingSenderId: '691213890190',
    projectId: 'nexevent-d5e5b',
    storageBucket: 'nexevent-d5e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyr0HBEmtmYzvGWWWWfkuB0pt_qXQHQU4',
    appId: '1:691213890190:ios:c9fe35862f215357798fdf',
    messagingSenderId: '691213890190',
    projectId: 'nexevent-d5e5b',
    storageBucket: 'nexevent-d5e5b.firebasestorage.app',
    iosBundleId: 'com.example.nexevent',
  );
}
